# Generated by Django 4.1.4 on 2022-12-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Doc_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=50)),
                ("age", models.CharField(max_length=2)),
                ("gender", models.CharField(max_length=7)),
                ("phone_no", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=200)),
                ("health_issue", models.CharField(max_length=200)),
                ("available_timings", models.TimeField()),
            ],
        ),
        migrations.DeleteModel(name="Clinic",),
    ]
