# Generated by Django 4.1.4 on 2023-01-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("b_app", "0002_profile_delete_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="title", new_name="user",
        ),
    ]
